### ISSUE TITLE
Messages are not sent

### ISSUE THREAD

**Issue by hilltty** [4drian3d/SignedVelocity#11]
When a user sends a message to the chat, nothing happens, I use the plugin on the proxy and on the backend server (Velocity + Purpur).

**Comment by hilltty** [comment]
Paper plugins:
`[21:11:12 INFO]: Paper Plugins: (1):
[21:11:12 INFO]:  - SignedVelocity
[21:11:12 INFO]: Bukkit Plugins: (2):
[21:11:12 INFO]:  - CommandWhitelist, spark`

Velocity plugins:
`[21:12:07 INFO]: Plugins: commandwhitelist, fastmotd, limboapi, limboauth, luckperms, neoprotect, signedvelocity, spicord, streamlinecore, velocity_tools`

**Comment by 4drian3d** [comment]
What version of SignedVelocity are you using?

**Comment by hilltty** [comment]
After updating to beta3 problem gone
