### ISSUE TITLE
Fabric still receives original Message when a plugin modifies said Message

### ISSUE THREAD

**Issue by Schmazda** [4drian3d/SignedVelocity#114]
I am using the latest version (1.2.4) using a 1.21 Fabric server and Velocity 3.3.0-SNAPSHOT-436

This happens when I use `ChatResult.message()` to remove the Prefix that specifies the desired Audience.
In this case the prefix symbolizes the MineCraft Server, i.e. the Vanilla Chat.
If this helps, here is the snippet of my Plugin's code: 
![image](https://github.com/user-attachments/assets/054c3d28-b15b-47f3-b3f9-bd1d45252789)
The Event is registered with `PostOrder.FIRST`, so it is definitely executed before SignedVelocity's EventListener. 

Here is what the Client receives:
![image](https://github.com/user-attachments/assets/4f4c64ea-d234-4792-acab-04814ab0fbff)
The first message is the expected/modified message; the second message is the original message.

**Comment by Schmazda** [comment]
For all Velocity Plugin devs reading this: an ugly hotfix is to just send the message to the `RegisteredServer` yourself and returning `ChatEvent.denied()` even when you just modify the messages content.

**Comment by 4drian3d** [comment]
![image](https://github.com/user-attachments/assets/ac68bb95-8a8a-41ac-9dd9-e73ad363e933)
Fixed, confirmed to work in Fabric 1.21.1, the next version will have the fix
