### ISSUE TITLE
Update to new Minestom

### ISSUE THREAD

**Issue by ajh123** [4drian3d/SignedVelocity#117]
Minestom has changed a lot since the last update to SignedVelocity's Minestom build:
1. Minestom CE is dead (it has merged into the orignal Minestom repo)
2. Minestom does not use Jit Pack, it is now on Maven Central
3. Minestom no longer uses extenstions, as it has been refactored into just a libaray for server creators. *(there is [minestom-ce-extensions](https://github.com/hollow-cube/minestom-ce-extensions/), however, it hasn't been updated to the new Minestom)*

This means you need to update your Gradle configs to point to the new Minestom, and refactor your Minestom code into a libaray the can be imported into a Minestom envrionment, many Minestom libaries do this now (for example [MinestomPVP](https://github.com/TogAr2/MinestomPvP).

It would be nice if you would publish SignedVelocity Minestom builds on a Maven repoistory, but, its completely optional, since, we can import Jars in Gradle / Maven.

**Comment by 4drian3d** [comment]
> It would be nice if you would publish SignedVelocity Minestom builds on a Maven repoistory

The next version will be published in Maven Central, thanks for making this issue

**Comment by 4drian3d** [comment]
https://s01.oss.sonatype.org/service/local/repositories/snapshots/archive/io/github/4drian3d/signedvelocity-minestom/1.3.0-SNAPSHOT/signedvelocity-minestom-1.3.0-20241104.045421-2-javadoc.jar/!/io/github/_4drian3d/signedvelocity/minestom/SignedVelocity.html#initialize()

I have already published the artifact in Sonatype Snapshots, when version 1.3.0 is released I will publish it in Maven Central
