### ISSUE TITLE
SignedVelocity and Litebans conflict

### ISSUE THREAD

**Issue by SrMonsterYT** [4drian3d/SignedVelocity#118]
when using this plugin with litebans in velocity, people can talk even when mutated, so I reported it to nChat he said that litebans just needs to block the AsyncPlayerChatEvent, so litebans said that it is blocking this, I assume that SignedVelocity is deactivating the AsyncPlayerChatEvent, so even when mutated anyone can talk even when mutated by the litebans plugin.

velocity plugins:

SignedVelocity-Proxy-1.2.4
LiteBans

Backend plugins:

SignedVelocity-Paper-1.2.4

**Comment by 4drian3d** [comment]
Unsupported plugin
