### ISSUE TITLE
Not compatible with latest version of Velocity 3.3.0-b329+

### ISSUE THREAD

**Issue by Athar42** [4drian3d/SignedVelocity#70]
Hi,

Since I did update from b327 to b330 of Velocity proxy, this plugin is not compatible anymore :

This is what I can get in the server log : 

> [11:45:37 INFO] [signedvelocity]: Starting SignedVelocity
> [11:45:37 ERROR]: Couldn't pass ProxyInitializeEvent to signedvelocity
> com.google.inject.ProvisionException: Unable to provision, see the following errors:
> 1) [Guice/ErrorInjectingConstructor]: NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/ServerData
>   at VPacketEventsAdapter.<init>(VPacketEventsAdapter.java:12)
>   while locating VPacketEventsAdapter
> Learn more:
>   https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
> 1 error
> ======================
> Full classname legend:
> ======================
> VPacketEventsAdapter: "io.github._4drian3d.signedvelocity.velocity.packet.VPacketEventsAdapter"
> ========================
> End of classname legend:
> ========================
>         at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at io.github._4drian3d.signedvelocity.velocity.packet.PacketAdapter.register(PacketAdapter.java:19) ~[?:?]
>         at io.github._4drian3d.signedvelocity.velocity.SignedVelocity.onProxyInitialization(SignedVelocity.java:48) ~[?:?]
>         at io.github._4drian3d.signedvelocity.velocity.Lmbda$8.execute(Unknown Source) ~[?:?]
>         at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
>         at java.lang.Thread.run(Thread.java:833) [?:?]
> Caused by: java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/ServerData
>         at io.github._4drian3d.signedvelocity.velocity.packet.VPacketEventsAdapter.<clinit>(VPacketEventsAdapter.java:17) ~[?:?]
>         at io.github._4drian3d.signedvelocity.velocity.packet.VPacketEventsAdapter$$FastClassByGuice$$175ded2.GUICE$TRAMPOLINE(<generated>) ~[?:?]
>         at io.github._4drian3d.signedvelocity.velocity.packet.VPacketEventsAdapter$$FastClassByGuice$$175ded2.apply(<generated>) ~[?:?]
>         at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         ... 10 more
> Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.ServerData
>         at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
>         at io.github._4drian3d.signedvelocity.velocity.packet.VPacketEventsAdapter.<clinit>(VPacketEventsAdapter.java:17) ~[?:?]
>         at io.github._4drian3d.signedvelocity.velocity.packet.VPacketEventsAdapter$$FastClassByGuice$$175ded2.GUICE$TRAMPOLINE(<generated>) ~[?:?]
>         at io.github._4drian3d.signedvelocity.velocity.packet.VPacketEventsAdapter$$FastClassByGuice$$175ded2.apply(<generated>) ~[?:?]
>         at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         ... 10 more

If you need someone to test a new release, I'm available to "beta test" it.
Same if you need some more infos, I'm here :P 

Edit : Did some more tests : 
Compatible until build 328 included.
Start to fail the initialization on build 329 and forward :)

**Comment by 4drian3d** [comment]
Try using this version https://github.com/4drian3d/SignedVelocity/actions/runs/7577043838

**Comment by Athar42** [comment]
Partial fix :) 

Seems to be OK for this package + SignedVelocity, but AuthMeVelocity fail : 

> [14:12:11 ERROR]: Couldn't pass ProxyInitializeEvent to authmevelocity
> java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/TabCompleteResponse
>         at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
>         at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
>         at java.lang.Class.getDeclaredMethods(Class.java:2504) ~[?:?]
>         at com.google.inject.internal.DeclaredMembers.getDeclaredMethods(DeclaredMembers.java:48) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.spi.InjectionPoint.getDeclaredMethods(InjectionPoint.java:816) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:735) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:431) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:177) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:686) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:629) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:615) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:990) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:902) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:302) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:225) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:1140) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1169) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1134) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at io.github._4drian3d.authmevelocity.velocity.AuthMeVelocityPlugin.onProxyInitialization(AuthMeVelocityPlugin.java:161) ~[?:?]
>         at io.github._4drian3d.authmevelocity.velocity.Lmbda$7.execute(Unknown Source) ~[?:?]
>         at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
>         at java.lang.Thread.run(Thread.java:833) [?:?]
> Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.TabCompleteResponse
>         at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
>         ... 27 more
> [14:12:11 INFO] [signedvelocity]: Starting SignedVelocity


Don't know if this is related to this plugin, or directly on AuthMeVelocity

**Comment by Athar42** [comment]
In waiting the update for AuthMeVelocity, I did rollback to build 328 (and with this new version of SignedVelocity), and the messages aren't signed when you are connected (the "in game message" (top right corner)).

So this new version may be specific starting build 329 :)

I'll confirm once the second plugin will be updated, so I could fully test and report here the end result.

**Comment by 4drian3d** [comment]
Sorry for the delay, I'm already working on the new update

**Comment by Athar42** [comment]
No hurry, I was just doing a statement update so you know that this new release may not be working for build of Velocity prior 329 (as we get the unsigned notification with Velocity 328).

Maybe need a condition check on startup (if build <329, execute old code, else new, don't know :D ) or do two seperate build, or a big warning on release :P
