### ISSUE TITLE
[Bug] Detect the AsynChatEvent

### ISSUE THREAD

**Issue by NoltoxGit** [4drian3d/SignedVelocity#72]
Hello,
I've enable an option in [DiscordSRV](https://github.com/DiscordSRV/DiscordSRV) for the AsyncChatEvent, but when i restart my server, SignedVelocity doesn't detect this.

Maybe the code for this [here](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/listeners/ModernPlayerChatListener.java).

**Comment by 4drian3d** [comment]
The DiscordSRV code works fine. SignedVelocity uses the most immediate priority and DiscordSRV uses the last priority in case you have enabled its configuration option, they are fully compatible
You should check that you are really activating that option because I have received confirmation that several people had it working perfectly

**Comment by NoltoxGit** [comment]
> The DiscordSRV code works fine. SignedVelocity uses the most immediate priority and DiscordSRV uses the last priority in case you have enabled its configuration option, they are fully compatible
> You should check that you are really activating that option because I have received confirmation that several people had it working perfectly

I've enabled the parameter in the configuration, and when I restart my server I still have DiscordSRV listed as not using the event. :/
![image](https://github.com/4drian3d/SignedVelocity/assets/75265787/7d9ca0bc-4a88-464e-bdbc-8eabf1c9f16b)
→ Logs: https://mclo.gs/cZvSwjD

**Comment by 4drian3d** [comment]
Well, you have more than 10 plugins that use deprecated chat events, try in a clean setup only with SignedVelocity and DiscordSRV

**Comment by NoltoxGit** [comment]
> Well, you have more than 10 plugins that use deprecated chat events, try in a clean setup only with SignedVelocity and DiscordSRV

I've made an issue of all plugins with this error, but some developers are reluctant to add it
