### ISSUE TITLE
1.12.2 version

### ISSUE THREAD

**Issue by SladeHazard** [4drian3d/SignedVelocity#73]
Hey would signedvelocity work for me if I'm running velocity proxy, 1.20.1 hub server and 1.12.2 prison server? I have installed the plugin with vpacketevents on my proxy & on the hub. but it seems like there is no version for older mc servers would I be fine with running it or would newer players connecting to my prison eventually get kicked?

**Comment by 4drian3d** [comment]
1.12.2 is an old and unsupported version
