### ISSUE TITLE
1.20.5 error

### ISSUE THREAD

**Issue by levlevin** [4drian3d/SignedVelocity#89]
Trying out latest 1.2.4 Snapshot. When set up on Velocity 3.3.0 (snapshots 385-388), Fabric 1.20.5 – I get the following error in the client:
<img width="966" alt="Screenshot 2024-05-02 at 14 41 18" src="https://github.com/4drian3d/SignedVelocity/assets/5635070/c0155b36-5140-45fa-92bb-aba8f3a66a09">

Previously my setup was based on 1.20.1, everything was working as expected.
Server logs on both backend and proxy do not tell anything more specific than the client.

**Comment by 4drian3d** [comment]
The latest version is not compatible with Fabric 1.20.5, I'm working on fixing that

**Comment by levlevin** [comment]
Hi @4drian3d! Did you manage to get this to work?

**Comment by 4drian3d** [comment]
fixed
